title: A daydream place for Yang
description: Hello, this is Yang Zhong, a software developer and giser
permalink: ':title/'
baseurl: '' # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Y.Z # add your name
author-img: new-head.jpg # add your photo
about-author: I am a software developer/giser. Always hungry to keep learning. # add description
twitter: yzhong1985 # add your Twitter handle
facebook: yang.zhong.3572 # add your Facebook handle
github: yzhong1985 # add your Github handle
linkedin: # add your Linkedin handle
email: yzhong1985@gmail.com # add your Email address

# Disqus
discus-identifier: yzhong1985-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
